#mp_core:
#  resource: '../src/Controller/'
#  type: attribute
#  prefix: /core

#controllers:
#  resource:
#    path: ../src/Controller/
#    namespace: MP\CoreBundle\Controller
#  type: attribute
mp_core:
  resource: '@CoreBundle/config/routes'
  type: directory
  prefix: /core

#home_index:
#  path: /home
#  controller: MP\CoreBundle\Controller::index