#mp_core:
#  resource: '../src/Controller/'
#  type: attribute
#  prefix: /core

#controllers:
#  resource:
#    path: ../src/Controller/
#    namespace: MP\CoreBundle\Controller
#  type: attribute

mp_core:
  path: /home
  controller: MP\CoreBundle\Controller::index