services:
  MP\CoreBundle\:
    resource: '../src/'
    public: true
    autowire: true
    autoconfigure: true

  MP\CoreBundle\src\Routing\CoreBundleLoader:
    tags: [routing.loader]

  app_index:
    resource: .
    type: autowire

