services:
  MP\CoreBundle\:
    resource: '../src/'
    public: true
    autowire: true
    autoconfigure: true

  MP\CoreBundle\Routing\CoreBundleLoader:
    arguments: [ ]
    tags:
      - { name: routing.loader }




