services:
  MP\CoreBundle\:
    resource: '../src/'
    public: true
    autowire: true
    autoconfigure: true

  MP\CoreBundle\Routing\CoreBundleLoader:
    tags: [ 'routing.loader' ]

  MP\CoreBundle\Controller\:
    resource: '../src/Controller'
    autowire: true
    autoconfigure: true
    public: true




