#services:
#  MP\CoreBundle\:
#    resource: '../src/'
#    public: true
#    autowire: true
#    autoconfigure: true

services:
  MP\CoreBundle\src\Controller:
    resource: '../src/Controller'
    public: true
    autowire: true
    autoconfigure: true

