controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mp_core:
  resource: '%kernel.project_dir%/vendor/mp/first-bundle/mp/core-bundle/src/Controller'
  type: directory
  prefix: /core