controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mp_core:
  resource: '../mp/core-bundle/src/Controller'
  type: directory
  prefix: /core